; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	H:\MinGW\home\other\meditor2\Libs\7z\Archive\7z\7zHeader.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_k7zSignature
_DATA	SEGMENT
_k7zSignature DB 037H
	DB	07aH
	DB	0bcH
	DB	0afH
	DB	027H
	DB	01cH
_DATA	ENDS
END
