//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MEditor2.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MEDITOR2_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_PLAYER_DIALOG               129
#define IDD_INPUT_DIALOG                130
#define IDR_MENU1                       131
#define IDD_ASSOS_DIALOG                131
#define IDD_PLAYER_DIALOG2              132
#define IDD_VIDEO_DIALOG                132
#define IDD_AUDIO_DIALOG                133
#define IDD_DECODE_DIALOG               134
#define IDD_OTHER_DIALOG                135
#define IDD_DIALOG_FLASHPLAYER          136
#define IDD_DIALOG_FLASH                136
#define IDR_MENU_FLASHPLAYER            141
#define IDR_MENU_FLASH                  141
#define IDD_DIALOG_LIST                 142
#define IDR_MENU_WMP                    142
#define IDR_MENU_REAL                   143
#define IDR_MENU_DSHOW                  143
#define IDI_ICON_SWF                    144
#define IDD_DIALOG_MEDIA                148
#define IDD_DIALOG_MLIST                149
#define IDI_ICON1                       150
#define IDI_ICON_DS                     150
#define IDD_RESUME_DIALOG               150
#define IDD_DIALOG_FLASH1               151
#define IDD_DIALOG_DSHOW                151
#define IDZ_CODECS_INI                  168
#define IDZ_CODECS                      168
#define IDZ_INPUT                       170
#define IDD_DIALOG_LINK                 171
#define IDC_TAB1                        1000
#define IDC_LIST_INPUT                  1001
#define IDC_APPLY                       1004
#define IDC_SHOWHELP                    1005
#define IDC_LIST_ASSOS                  1006
#define IDC_ADD                         1007
#define IDC_ALL                         1008
#define IDC_NONE                        1009
#define IDC_RECOMMAND                   1010
#define IDC_DEL                         1011
#define IDC_ASSOS                       1012
#define IDC_PROGRESS_APPLEY             1013
#define IDC_COMBO_MONITOR               1015
#define IDC_COMBO_AUTOSYNC              1016
#define IDC_COMBO_LANGUAGE              1017
#define IDC_COMBO_SIZE                  1018
#define IDC_CHECK_URL                   1019
#define IDC_CHECK_FULLSCREEN            1020
#define IDC_CHECK_ONLYONE               1021
#define IDC_COMBO_LOG                   1022
#define IDC_COMBO_COLOR                 1022
#define IDC_COMBO_PRIORITY              1023
#define IDC_COMBO_BCOLOR                1023
#define IDC_COMBO_LOOP                  1024
#define IDC_COMBO_FUZZINESS             1024
#define IDC_COMBO_ONTOP                 1025
#define IDC_COMBO_ALIGN                 1025
#define IDC_CHECK_FRAMEDROP             1026
#define IDC_COMBO_OSDSIZE               1026
#define IDC_COMBO_AUTOSCALE             1026
#define IDC_EDIT_PNG                    1027
#define IDC_CHECK_DR                    1027
#define IDC_CHECK_INDEX                 1028
#define IDC_CHECK_REINDEX               1028
#define IDC_CHECK_AUTOPLAY              1029
#define IDC_CHECK_SHOW                  1030
#define IDC_CHECK_QUIT                  1031
#define IDC_CHECK_GUITHREAD             1032
#define IDC_BUTTON_PNG                  1033
#define IDC_EDIT_DVD                    1034
#define IDC_BUTTON_DVD                  1035
#define IDC_EDIT_START                  1036
#define IDC_EDIT_END                    1037
#define IDC_CHECK_ASS                   1038
#define IDC_CHECK_MENU                  1038
#define IDC_CHECK_MENU2                 1039
#define IDC_CHECK_CTRL                  1039
#define IDC_CHECK_HIDE                  1039
#define IDC_EDIT_ERROR                  1040
#define IDC_CHECK_SYS                   1040
#define IDC_CHECK_DVDSUB                1041
#define IDC_CHECK_OSD                   1041
#define IDC_COMBO_OSDTIME               1041
#define IDC_SLIDER_VOLUME               1042
#define IDC_CHECK_FLASH                 1042
#define IDC_COMBO_OSDMODE               1042
#define IDC_EDIT_VOLUME                 1043
#define IDC_SLIDER_BRINGHTNESS          1043
#define IDC_CHECK_QUIET                 1043
#define IDC_EDIT_BRINGHTNESS            1044
#define IDC_EDIT_SUBPOS                 1044
#define IDC_CHECK_DOUBLE                1044
#define IDC_EDIT_SUBDELAY               1045
#define IDC_CHECK_KEEPAS                1045
#define IDC_COMBO_COLORKEY              1045
#define IDC_EDIT_AUDIODELAY             1046
#define IDC_COMBO_CACHE                 1046
#define IDC_SLIDER_VOLNORM              1047
#define IDC_CHECK_CONF                  1047
#define IDC_EDIT_VOLNORM                1048
#define IDC_COMBO_VIEW                  1048
#define IDC_LIST_AUDIO                  1049
#define IDC_SLIDER_SATURATIONS          1049
#define IDC_CHECK_BOTTOM                1049
#define IDC_COMBO_AUDIO                 1050
#define IDC_EDIT_SATURATIONS            1050
#define IDC_COMBO_SYSTRAY               1050
#define IDC_COMBO_CHANNELS              1051
#define IDC_SLIDER_HUE                  1051
#define IDC_COMBO_AUTOPLAY              1051
#define IDC_EDIT_HUE                    1052
#define IDC_EDIT_SLANG                  1052
#define IDC_EDIT_SUBCP                  1053
#define IDC_SLIDER_GAMMA                1053
#define IDC_EDIT_GAMMA                  1054
#define IDC_COMBO_OSDF                  1056
#define IDC_COMBO_F1                    1057
#define IDC_COMBO_F2                    1058
#define IDC_COMBO_VO                    1060
#define IDC_CHECK_SOFT                  1061
#define IDC_COMBO_MXCOLOR               1062
#define IDC_EDIT_COLOR                  1064
#define IDC_BUTTON_COLOR                1065
#define IDC_LIST_VF                     1066
#define IDC_SLIDER_CONTRAST             1068
#define IDC_EDIT_CONTRAST               1069
#define IDC_LIST_VC                     1072
#define IDC_LIST_AC                     1073
#define IDC_BUTTON_ADD                  1074
#define IDC_BUTTON_DEL                  1075
#define IDC_BUTTON_DOWN                 1076
#define IDC_BUTTON_UP                   1077
#define IDC_BUTTON_ADD2                 1078
#define IDC_BUTTON_DEL2                 1079
#define IDC_BUTTON_DOWN2                1080
#define IDC_BUTTON_UP2                  1081
#define IDC_CHECK_PAGE                  1082
#define IDC_LIST_AVCODEC                1082
#define IDC_EDIT_OTHER                  1083
#define IDC_CHECK_ONE                   1084
#define IDC_EDIT_VIDEO                  1085
#define IDC_EDIT_AUDIO                  1086
#define IDC_BUTTON_VIDEO                1087
#define IDC_BUTTON_AUDIO                1088
#define IDC_BUTTON_PLAY                 1089
#define IDC_BUTTON_CLEAN                1090
#define IDC_SHOCKWAVEFLASH              1090
#define IDC_SLIDER_CONTROL              1091
#define IDC_BUTTON_FLASH                1091
#define IDC_BUTTON_LINK                 1092
#define IDC_PLAYLIST                    1094
#define IDC_BUTTON_REAL                 1098
#define IDC_BUTTON_MEDIA                1098
#define IDC_BUTTON_ONLINE               1099
#define IDC_BUTTON_DONLINE              1100
#define IDC_CHECK_VISTA                 1101
#define IDC_RADIO_MPLAYER               1102
#define IDC_RADIO_MEDITOR               1103
#define IDC_OCX1                        1106
#define IDC_OCX_MEDIA                   1106
#define IDC_SLIDER_CTRL                 1107
#define IDC_LIST_RESUME                 1108
#define IDC_CHECK1                      1109
#define IDC_CHECK_RESUME                1109
#define IDC_CHECK_RMENU                 1109
#define IDC_CHECK2                      1110
#define IDC_CHECK_RMENU2                1110
#define IDC_CHECK3                      1111
#define IDC_CHECK_MPC                   1111
#define IDC_CHECK4                      1112
#define IDC_CHECK5                      1113
#define IDC_BUTTON_CLA                  1114
#define IDC_CHECK6                      1114
#define IDC_REALPLAYER1                 1115
#define IDC_CHECK7                      1115
#define IDC_EDIT_NUM                    1121
#define IDC_EDIT_FUZZINESS              1122
#define IDC_COMBO_CODECS                1124
#define IDC_C_MPC                       1126
#define IDC_CHECK8                      1126
#define ID_32771                        32771
#define ID_CANCLE                       32772
#define ID_CAN                          32773
#define ID_APP_HELPFILE                 32774
#define ID_FLASH_OPEN                   32775
#define ID_MPLAYLIST                    32776
#define ID_MPLAY                        32777
#define ID_MSTOP                        32778
#define ID_MNEXT                        32781
#define ID_MPRE                         32782
#define ID_MEDIA_OPEN                   32783
#define IDM_PLAY                        32784
#define IDM_STOP                        32785
#define IDM_NEXT                        32786
#define IDM_PREV                        32787
#define IDM_FULLSCREEN                  32788
#define IDM_RMENU                       32790
#define IDM_RIGHTMENU                   32791
#define IDM_PLAYLIST                    32792
#define ID_REAL_OPEN                    32793
#define IDM_RPLAY                       32794
#define IDM_RSTOP                       32795
#define IDM_RPREV                       32796
#define IDM_NORMAL                      32797
#define IDM_HIGH                        32798
#define ID_32799                        32799
#define IDM_LOWER                       32800
#define ID_32801                        32801
#define ID_32802                        32802
#define ID_32803                        32803
#define ID_32804                        32804
#define ID_MPLAYER_INI                  32805
#define ID_INPUT_INI                    32806
#define ID_KK_INI                       32807
#define ID_LOG_TXT                      32808
#define ID_32809                        32809
#define ID_Menu                         32810
#define IDM_ABOUT                       32811
#define ID_DS_OPEN                      32812
#define IDM_DSPLAY                      32813
#define IDM_DSSTOP                      32814
#define IDM_DSFULLSCREEN                32815

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32816
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
