//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MEditor2.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MEDITOR2_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_PLAYER_DIALOG               129
#define IDD_INPUT_DIALOG                130
#define IDR_MENU1                       131
#define IDD_ASSOS_DIALOG                131
#define IDD_PLAYER_DIALOG2              132
#define IDD_VIDEO_DIALOG                132
#define IDD_AUDIO_DIALOG                133
#define IDD_DECODE_DIALOG               134
#define IDD_OTHER_DIALOG                135
#define IDR_MENU_FLASH                  141
#define IDD_DIALOG_LIST                 142
#define IDR_MENU_WMP                    142
#define IDR_MENU_REAL                   143
#define IDR_MENU_DSHOW                  143
#define IDI_ICON_SWF                    144
#define IDD_DIALOG_FLASH                145
#define IDD_DIALOG_MEDIA                148
#define IDD_DIALOG_MLIST                149
#define IDI_ICON1                       150
#define IDI_ICON_DS                     150
#define IDD_RESUME_DIALOG               150
#define IDD_DIALOG_FLASH1               151
#define IDD_DIALOG_DSHOW                151
#define IDZ_CODECS_INI                  168
#define IDZ_CODECS                      168
#define IDZ_INPUT                       170
#define IDD_DIALOG_LINK                 171
#define IDD_DIALOG_PROFILE_ADD          175
#define IDD_DIALOG_INFO                 176
#define IDD_DIALOG_MEDIAINFO            179
#define IDD_PROFILE_DIALOG              190
#define IDD_OSD_DIALOG                  191
#define IDD_SUBTITLE_DIALOG             191
#define IDD_PLAYER_DIALOG_EN            192
#define IDD_PLAYER_DIALOG_TC            193
#define IDD_ASSOS_DIALOG_EN             194
#define IDD_AUDIO_DIALOG_EN             195
#define IDD_DECODE_DIALOG_EN            196
#define IDD_INPUT_DIALOG_EN             197
#define IDD_OTHER_DIALOG_EN             198
#define IDD_PROFILE_DIALOG_EN           199
#define IDD_RESUME_DIALOG_EN            200
#define IDD_SUBTITLE_DIALOG_EN          201
#define IDD_VIDEO_DIALOG_EN             202
#define IDD_VIDEO_DIALOG_TC             203
#define IDD_SUBTITLE_DIALOG_TC          204
#define IDD_RESUME_DIALOG_TC            205
#define IDD_PROFILE_DIALOG_TC           206
#define IDD_OTHER_DIALOG_TC             207
#define IDD_INPUT_DIALOG_TC             208
#define IDD_AUDIO_DIALOG_TC             209
#define IDD_ASSOS_DIALOG_TC             210
#define IDD_DECODE_DIALOG_TC            211
#define IDC_TAB1                        1000
#define IDC_LIST_INPUT                  1001
#define IDC_APPLY                       1004
#define IDC_SHOWHELP                    1005
#define IDC_LIST_ASSOS                  1006
#define IDC_ADD                         1007
#define IDC_ALL                         1008
#define IDC_NONE                        1009
#define IDC_RECOMMAND                   1010
#define IDC_DEL                         1011
#define IDC_ASSOS                       1012
#define IDC_PROGRESS_APPLEY             1013
#define IDC_COMBO_MONITOR               1015
#define IDC_COMBO_AUTOSYNC              1016
#define IDC_COMBO_LANGUAGE              1017
#define IDC_COMBO_SIZE                  1018
#define IDC_CHECK_URL                   1019
#define IDC_CHECK_FULLSCREEN            1020
#define IDC_CHECK_ONLYONE               1021
#define IDC_COMBO_LOG                   1022
#define IDC_COMBO_COLOR                 1022
#define IDC_COMBO_PRIORITY              1023
#define IDC_COMBO_BCOLOR                1023
#define IDC_COMBO_LOOP                  1024
#define IDC_COMBO_FUZZINESS             1024
#define IDC_COMBO_ONTOP                 1025
#define IDC_COMBO_ALIGN                 1025
#define IDC_CHECK_FRAMEDROP             1026
#define IDC_COMBO_AUTOSCALE             1026
#define IDC_EDIT_PNG                    1027
#define IDC_CHECK_DR                    1027
#define IDC_COMBO_ASSEXPAND             1027
#define IDC_COMBO_OSDSIZE               1028
#define IDC_CHECK_INDEX                 1028
#define IDC_CHECK_REINDEX               1028
#define IDC_EDIT_DEF                    1028
#define IDC_CHECK_AUTOPLAY              1029
#define IDC_CHECK_SHOW                  1030
#define IDC_CHECK_QUIT                  1031
#define IDC_CHECK_GUITHREAD             1032
#define IDC_BUTTON_PNG                  1033
#define IDC_EDIT_DVD                    1034
#define IDC_BUTTON_DVD                  1035
#define IDC_EDIT_START                  1036
#define IDC_EDIT_END                    1037
#define IDC_CHECK_ASS                   1038
#define IDC_CHECK_MENU                  1038
#define IDC_CHECK_MENU2                 1039
#define IDC_CHECK_CTRL                  1039
#define IDC_CHECK_HIDE                  1039
#define IDC_CHECK_ASS_MARGINS           1039
#define IDC_CHECK_NOSKIN                1039
#define IDC_EDIT_ERROR                  1040
#define IDC_CHECK_SYS                   1040
#define IDC_BUTTON_DEF                  1040
#define IDC_CHECK_DVDSUB                1041
#define IDC_CHECK_OSD                   1041
#define IDC_COMBO_OSDTIME               1041
#define IDC_CHECK_TITLE                 1041
#define IDC_SLIDER_VOLUME               1042
#define IDC_CHECK_FLASH                 1042
#define IDC_EDIT_FSCALE                 1042
#define IDC_EDIT_VOLUME                 1043
#define IDC_SLIDER_BRINGHTNESS          1043
#define IDC_CHECK_QUIET                 1043
#define IDC_COMBO_OSDMODE               1043
#define IDC_EDIT_BRINGHTNESS            1044
#define IDC_EDIT_SUBPOS                 1044
#define IDC_CHECK_DOUBLE                1044
#define IDC_EDIT_SUBDELAY               1045
#define IDC_CHECK_KEEPAS                1045
#define IDC_COMBO_COLORKEY              1045
#define IDC_EDIT_AUDIODELAY             1046
#define IDC_COMBO_CACHE                 1046
#define IDC_CHECK_VISTA_FS              1046
#define IDC_SLIDER_VOLNORM              1047
#define IDC_CHECK_CONF                  1047
#define IDC_EDIT_VOLNORM                1048
#define IDC_COMBO_VIEW                  1048
#define IDC_LIST_AUDIO                  1049
#define IDC_SLIDER_SATURATIONS          1049
#define IDC_CHECK_BUTTON                1049
#define IDC_CHECK_CONSOLE               1049
#define IDC_COMBO_AUDIO                 1050
#define IDC_EDIT_SATURATIONS            1050
#define IDC_COMBO_SYSTRAY               1050
#define IDC_COMBO_CHANNELS              1051
#define IDC_SLIDER_HUE                  1051
#define IDC_COMBO_AUTOPLAY              1051
#define IDC_EDIT_HUE                    1052
#define IDC_EDIT_SLANG                  1052
#define IDC_CHECK_HTIMER                1052
#define IDC_EDIT_SUBCP                  1053
#define IDC_SLIDER_GAMMA                1053
#define IDC_CHECK_STATUS                1053
#define IDC_COMBO_AUTOPLAY2             1053
#define IDC_EDIT_GAMMA                  1054
#define IDC_EDIT_ALANG                  1054
#define IDC_CHECK_DVDNAV                1054
#define IDC_CHECK_AUTOSUB               1055
#define IDC_CHECK_RELOAD                1055
#define IDC_COMBO_OSDF                  1056
#define IDC_CHECK_BOOST                 1056
#define IDC_COMBO_OSDFONT               1056
#define IDC_COMBO_F1                    1057
#define IDC_CHECK_BOOST2                1057
#define IDC_CHECK_GUI                   1057
#define IDC_COMBO_F2                    1058
#define IDC_COMBO_ALPHA                 1058
#define IDC_COMBO_CTRLBAR               1059
#define IDC_COMBO_VO                    1060
#define IDC_CHECK_SOFT                  1061
#define IDC_COMBO_MXCOLOR               1062
#define IDC_EDIT_COLOR                  1064
#define IDC_BUTTON_COLOR                1065
#define IDC_LIST_VF                     1066
#define IDC_EDIT_COLORP                 1066
#define IDC_BUTTON_COLORO               1067
#define IDC_SLIDER_CONTRAST             1068
#define IDC_EDIT_COLORO                 1068
#define IDC_EDIT_CONTRAST               1069
#define IDC_BUTTON_COLORS               1069
#define IDC_BUTTON_COLORB               1070
#define IDC_EDIT_COLORB                 1071
#define IDC_LIST_VC                     1072
#define IDC_EDIT_OUTLINE                1072
#define IDC_LIST_AC                     1073
#define IDC_EDIT_SHADOW                 1073
#define IDC_BUTTON_ADD                  1074
#define IDC_BUTTON_DEL                  1075
#define IDC_BUTTON_DOWN                 1076
#define IDC_BUTTON_UP                   1077
#define IDC_BUTTON_ADD2                 1078
#define IDC_BUTTON_DEL2                 1079
#define IDC_BUTTON_DOWN2                1080
#define IDC_BUTTON_UP2                  1081
#define IDC_CHECK_PAGE                  1082
#define IDC_LIST_AVCODEC                1082
#define IDC_EDIT_OTHER                  1083
#define IDC_CHECK_ONE                   1084
#define IDC_EDIT_VIDEO                  1085
#define IDC_EDIT_AUDIO                  1086
#define IDC_BUTTON_VIDEO                1087
#define IDC_BUTTON_AUDIO                1088
#define IDC_BUTTON_PLAY                 1089
#define IDC_BUTTON_CLEAN                1090
#define IDC_SHOCKWAVEFLASH              1090
#define IDC_SLIDER_CONTROL              1091
#define IDC_BUTTON_FLASH                1091
#define IDC_BUTTON_LINK                 1092
#define IDC_CHECK_XPTOOLBARS            1093
#define IDC_PLAYLIST                    1094
#define IDC_CHECK_XPWINDOW              1094
#define IDC_CHECK_XPTOOLBARS2           1095
#define IDC_CHECK_SCREENSAVER           1095
#define IDC_CHECK_THEME                 1096
#define IDC_BUTTON_REAL                 1098
#define IDC_BUTTON_MEDIA                1098
#define IDC_BUTTON_ONLINE               1099
#define IDC_BUTTON_DONLINE              1100
#define IDC_CHECK_VISTA                 1101
#define IDC_BUTTON_ONLINE2              1101
#define IDC_BUTTON_AVS                  1101
#define IDC_RADIO_MPLAYER               1102
#define IDC_RADIO_MEDITOR               1103
#define IDC_OCX1                        1106
#define IDC_OCX_MEDIA                   1106
#define IDC_SLIDER_CTRL                 1107
#define IDC_LIST_RESUME                 1108
#define IDC_CHECK1                      1109
#define IDC_CHECK_RESUME                1109
#define IDC_CHECK_RMENU                 1109
#define IDC_CHECK2                      1110
#define IDC_CHECK_RMENU2                1110
#define IDC_CHECK3                      1111
#define IDC_CHECK_MPC                   1111
#define IDC_CHECK4                      1112
#define IDC_CHECK5                      1113
#define IDC_BUTTON_CLA                  1114
#define IDC_CHECK6                      1114
#define IDC_REALPLAYER1                 1115
#define IDC_CHECK7                      1115
#define IDC_EDIT_NUM                    1121
#define IDC_EDIT_FUZZINESS              1122
#define IDC_COMBO_CODECS                1124
#define IDC_C_MPC                       1126
#define IDC_CHECK8                      1126
#define IDC_COMBO_EXTENSINO             1127
#define IDC_BUTTON1                     1128
#define IDC_BUTTON2                     1129
#define IDC_LIST_PROFILE                1130
#define IDC_COMBO1                      1131
#define IDC_COMBO_PROFILE               1131
#define IDC_STATIC_INFO                 1132
#define IDC_CHECK_INFO                  1133
#define IDC_CHECK_RIGHTMENU             1134
#define IDC_COMBO_OSD_TIME              1134
#define IDC_COMBO_OSD_SIZE              1135
#define IDC_CHECK_PRECENT               1136
#define IDC_CHECK_PERCENT               1136
#define IDC_BUTTON_COLORP               1138
#define IDC_CHECKP                      1139
#define IDC_CHECKS                      1140
#define IDC_CHECKO                      1141
#define IDC_CHECKB                      1142
#define IDC_EDIT_COLORS                 1143
#define IDC_CHECKWO                     1144
#define IDC_RADIOAUTO                   1144
#define IDC_CHECKWB                     1145
#define IDC_RADIOMANUAL                 1145
#define IDC_EXPLORER_HTML               1145
#define IDC_CHECK_FONTCONFIG            1148
#define IDC_CHECK_B                     1149
#define IDC_CHECK_I                     1150
#define IDC_CHECK_THREAD                1150
#define IDC_COMBO_MICONS                1151
#define ID_CANCLE                       32772
#define ID_CAN                          32773
#define ID_APP_HELPFILE                 32774
#define ID_FLASH_OPEN                   32775
#define ID_MPLAYLIST                    32776
#define ID_MPLAY                        32777
#define ID_MSTOP                        32778
#define ID_MNEXT                        32781
#define ID_MPRE                         32782
#define ID_MEDIA_OPEN                   32783
#define IDM_PLAY                        32784
#define IDM_STOP                        32785
#define IDM_NEXT                        32786
#define IDM_PREV                        32787
#define IDM_FULLSCREEN                  32788
#define IDM_RMENU                       32790
#define IDM_RIGHTMENU                   32791
#define IDM_PLAYLIST                    32792
#define ID_REAL_OPEN                    32793
#define IDM_RPLAY                       32794
#define IDM_RSTOP                       32795
#define IDM_RPREV                       32796
#define IDM_NORMAL                      32797
#define IDM_HIGH                        32798
#define IDM_LOWER                       32800
#define ID_MPLAYER_INI                  32805
#define ID_INPUT_INI                    32806
#define ID_KK_INI                       32807
#define ID_LOG_TXT                      32808
#define ID_Menu                         32810
#define IDM_ABOUT                       32811
#define ID_DS_OPEN                      32812
#define IDM_DSPLAY                      32813
#define IDM_DSSTOP                      32814
#define IDM_DSFULLSCREEN                32815
#define IDC_GOTOHOME                    32817
#define IDC_SHOWLOG                     32819
#define IDC_SHOWFAQ                     32821
#define IDC_SHOW_HELP                   32822
#define IDC_RESETINFO                   32825
#define IDS_PLAYER_NAME                 34999
#define IDS_TAB_PLAYER                  35000
#define IDS_TAB_VIDEO                   35001
#define IDS_TAB_AUDIO                   35002
#define IDS_TAB_DECODE                  35003
#define IDS_TAB_RESUME                  35004
#define IDS_TAB_OTHER                   35005
#define IDS_TAB_INPUT                   35006
#define IDS_TAB_ASSOS                   35007
#define IDS_PLAYER_AUTOSEL              35008
#define IDS_PLAYER_AUTO                 35009
#define IDS_PLAYER_NONE                 35010
#define IDS_PLAYER_PLAYING              35011
#define IDS_PLAYER_NO                   35012
#define IDS_PLAYER_AS_NO                35013
#define IDS_PLAYER_AS_NORMAL            35014
#define IDS_PLAYER_AS_FAST              35015
#define IDS_PLAYER_AS_FLV               35016
#define IDS_PLAYER_AS_FLVEX             35017
#define IDS_PLAYER_AS_AVI               35018
#define IDS_PLAYER_PREALTIME            35019
#define IDS_PLAYER_PHIGH                35020
#define IDS_PLAYER_PHNORMAL             35021
#define IDS_PLAYER_PNORMAL              35022
#define IDS_PLAYER_PLNORMAL             35023
#define IDS_PLAYER_PIDLE                35024
#define IDS_PLAYER_FILE                 35025
#define IDS_PLAYER_LIST                 35026
#define IDS_PLAYER_LOG_NO               35027
#define IDS_PLAYER_LOG                  35028
#define IDS_PLAYER_LOG_V1               35029
#define IDS_PLAYER_LOG_V2               35030
#define IDS_PLAYER_LOG_V3               35031
#define IDS_PLAYER_LOG_V4               35032
#define IDS_PLAYER_LOG_V5               35033
#define IDS_PLAYER_HIDE_NO              35034
#define IDS_PLAYER_HIDE_M               35035
#define IDS_PLAYER_HIDE_A               35036
#define IDS_PLAYER_NOTIME               35037
#define IDS_PLAYER_T1                   35038
#define IDS_PLAYER_T2                   35039
#define IDS_PLAYER_T3                   35040
#define IDS_PLAYER_T4                   35041
#define IDS_PLAYER_T5                   35042
#define IDS_PLAYER_T6                   35043
#define IDS_PLAYER_T7                   35044
#define IDS_PLAYER_T8                   35045
#define IDS_PLAYER_T9                   35046
#define IDS_PLAYER_NORMAL_MODE          35047
#define IDS_PLAYER_SHOWTIME             35048
#define IDS_PLAYER_SHOWREMAIN           35049
#define IDS_PLAYER_NOOSD                35050
#define IDS_PLAYER_TASK                 35051
#define IDS_PLAYER_TRAY                 35052
#define IDS_PLAYER_TRAYSTOP             35053
#define IDS_PLAYER_NOUSE                35054
#define IDS_PLAYER_EX                   35055
#define IDS_PLAYER_ALLWAYS              35056
#define IDS_RESUME_NORMAL               35057
#define IDS_RESUME_NO                   35058
#define IDS_RESUME_TIME                 35059
#define IDS_RESUME_FILE                 35060
#define IDS_PLAYER_SAMEDIR              35061
#define IDS_ASSOS_LIST                  35062
#define IDS_ASSOS_V                     35063
#define IDS_ASSOS_A                     35064
#define IDS_ASSOS_FLASH                 35065
#define IDS_ASSOS_DS                    35066
#define IDS_ASSOS_MV                    35067
#define IDS_ASSOS_MA                    35068
#define IDS_ASSOS_LA                    35069
#define IDS_ASSOS_LISTFILE              35070
#define IDS_ASSOS_MOV                   35071
#define IDS_ASSOS_AVI                   35072
#define IDS_ASSOS_CT                    35073
#define IDS_ASSOS_INPUT                 35074
#define IDS_ASSOS_AS                    35075
#define IDS_ASSOS_DEL                   35076
#define IDS_PLAYER_USE                  35077
#define IDS_ASSOS_OP                    35078
#define IDS_ASSOS_PL                    35079
#define IDS_ASSOS_ASSOS                 35080
#define IDS_ASSOS_EX                    35081
#define IDS_ASSOS_INF                   35082
#define IDS_ASSOS_TYP                   35083
#define IDS_OTHER_REALONLINE            35084
#define IDS_OTHER_REALOK                35085
#define IDS_OTHER_REALFAIL              35086
#define IDS_OTHER_REALAGAIN             35087
#define IDS_OTHER_REALON                35088
#define IDS_OTHER_REALFAILS             35089
#define IDS_OTHER_UNREALFAIL            35090
#define IDS_OTHER_UNREALOK              35091
#define IDS_OTHER_UNREALFAILS           35092
#define IDS_OTHER_OPENA                 35093
#define IDS_OTHER_OPENV                 35094
#define IDS_OTHER_TYPEA                 35095
#define IDS_OTHER_TYPEV                 35096
#define IDS_OTHER_ALL                   35097
#define IDS_OTHER_EMPTY                 35098
#define IDS_OTHER_LINK_EDITOR           35099
#define IDS_OTHER_LINK_PLAYER           35100
#define IDS_OTHER_TOOL1                 35101
#define IDS_OTHER_TOOL2                 35102
#define IDS_OTHER_TOOL3                 35103
#define IDS_OTHER_TOOL4                 35104
#define IDS_OTHER_TOOL5                 35105
#define IDS_OTHER_TOOL6                 35106
#define IDS_OTHER_TOOL7                 35107
#define IDS_OTHER_TOOL8                 35108
#define IDS_OTHER_TOOL9                 35109
#define IDS_TAB_AUDIO2                  35109
#define IDS_TAB_SUBTITLE                35109
#define IDS_OTHER_TOOL10                35110
#define IDS_DECODE_PR                   35112
#define IDS_DECODE_NAME                 35113
#define IDS_PLAYER_OPTION               35114
#define IDS_DECODE_INF                  35115
#define IDS_DECODE_SKIP1                35116
#define IDS_DECODE_SKIP2                35117
#define IDS_DECODE_SKIP3                35118
#define IDS_DECODE_SKIP4                35119
#define IDS_DECODE_SKIP5                35120
#define IDS_DECODE_CODEFILE1            35121
#define IDS_DECODE_CODEFILE2            35122
#define IDS_DECODE_CODEFILE3            35123
#define IDS_DECODE_SKIPLOOP             35124
#define IDS_DECODE_SKIPLOOP_INFO        35125
#define IDS_DECODE_SKIPFRAME            35126
#define IDS_DECODE_SKIPFRAME_INFO       35127
#define IDS_DECODE_XY                   35128
#define IDS_DECODE_XY_INFO              35129
#define IDS_DECODE_LOW                  35130
#define IDS_DECODE_LOW_INFO             35131
#define IDS_PLAYER_FNAME                35132
#define IDS_PLAYER_FINFO                35133
#define IDS_AUDIO_RELOW                 35134
#define IDS_AUDIO_REINT                 35135
#define IDS_AUDIO_REFOA                 35136
#define IDS_SUB_NORMAL_COL              35137
#define IDS_AUDIO_AFAT                  35138
#define IDS_AUDIO_AFH                   35139
#define IDS_AUDIO_AFF                   35140
#define IDS_AUDIO_RS                    35141
#define IDS_AUDIO_RM                    35142
#define IDS_AUDIO_VNL                   35143
#define IDS_AUDIO_VNL_INFO              35144
#define IDS_AUDIO_RE                    35145
#define IDS_AUDIO_RE_INFO               35146
#define IDS_AUDIO_EQ                    35147
#define IDS_AUDIO_EQ_INFO               35148
#define IDS_AUDIO_CHAN                  35149
#define IDS_AUDIO_DS                    35150
#define IDS_AUDIO_WIN                   35151
#define IDS_AUDIO_FILE                  35152
#define IDS_AUDIO_NULL                  35153
#define IDS_AUDIO_ADV                   35154
#define IDS_AUDIO_ADV_INFO              35155
#define IDS_SUB_FUZZ1                   35156
#define IDS_SUB_FUZZ2                   35157
#define IDS_SUB_FUZZ3                   35158
#define IDS_SUB_ALIG1                   35159
#define IDS_SUB_ALIG2                   35160
#define IDS_SUB_ALIG3                   35161
#define IDS_SUB_SCAL1                   35162
#define IDS_SUB_SCAL2                   35163
#define IDS_SUB_SCAL3                   35164
#define IDS_SUB_SCAL4                   35165
#define IDS_VIDEO_ROTA1                 35166
#define IDS_VIDEO_ROTA2                 35167
#define IDS_VIDEO_ROTA3                 35168
#define IDS_VIDEO_ROTA4                 35169
#define IDS_VIDEO_VD1                   35170
#define IDS_VIDEO_VD2                   35171
#define IDS_VIDEO_VD3                   35172
#define IDS_VIDEO_DB1                   35173
#define IDS_VIDEO_DB2                   35174
#define IDS_VIDEO_DB3                   35175
#define IDS_VIDEO_DB4                   35176
#define IDS_VIDEO_DB5                   35177
#define IDS_VIDEO_DB6                   35178
#define IDS_VIDEO_VO1                   35179
#define IDS_VIDEO_VO2                   35180
#define IDS_VIDEO_VOGL                  35180
#define IDS_VIDEO_VO3                   35181
#define IDS_VIDEO_VO4                   35182
#define IDS_VIDEO_VO5                   35183
#define IDS_VIDEO_VO6                   35184
#define IDS_VIDEO_VO7                   35185
#define IDS_VIDEO_VO8                   35186
#define IDS_VIDEO_VO9                   35187
#define IDS_VIDEO_VO10                  35188
#define IDS_VIDEO_MX1                   35189
#define IDS_VIDEO_MX2                   35190
#define IDS_VIDEO_MX3                   35191
#define IDS_VIDEO_MX4                   35192
#define IDS_VIDEO_COLMORE               35193
#define IDS_VIDEO_COLAT                 35194
#define IDS_VIDEO_SST                   35195
#define IDS_VIDEO_SSTI                  35196
#define IDS_VIDEO_ASS                   35197
#define IDS_VIDEO_ASSI                  35198
#define IDS_VIDEO_EXP                   35199
#define IDS_VIDEO_EXPI                  35200
#define IDS_VIDEO_EXPIT                 35201
#define IDS_VIDEO_ASP                   35202
#define IDS_VIDEO_ASPI                  35203
#define IDS_VIDEO_EQ2                   35204
#define IDS_VIDEO_EQ2I                  35205
#define IDS_VIDEO_HUE                   35206
#define IDS_VIDEO_HUEI                  35207
#define IDS_VIDEO_FLP                   35208
#define IDS_VIDEO_FLPI                  35209
#define IDS_VIDEO_ROT                   35210
#define IDS_VIDEO_ROTI                  35211
#define IDS_VIDEO_CRO                   35212
#define IDS_VIDEO_CROI                  35213
#define IDS_VIDEO_CROIT                 35214
#define IDS_VIDEO_DEI                   35215
#define IDS_VIDEO_DEII                  35216
#define IDS_VIDEO_DEB                   35217
#define IDS_VIDEO_DEBI                  35218
#define IDS_VIDEO_DER                   35219
#define IDS_VIDEO_DERI                  35220
#define IDS_VIDEO_TNO                   35221
#define IDS_VIDEO_TNOI                  35222
#define IDS_VIDEO_ATL                   35223
#define IDS_VIDEO_ATLI                  35224
#define IDS_VIDEO_OTH                   35225
#define IDS_VIDEO_OTHI                  35226
#define IDS_TAB_PROFILE                 35227
#define IDS_PROFILE_FLV                 35228
#define IDS_PROFILE_FLV_INFO            35229
#define IDS_PROFILE_ALN                 35230
#define IDS_PROFILE_ALN_INFO            35231
#define IDS_PROFILE_SLN                 35232
#define IDS_PROFILE_SLN_INFO            35233
#define IDS_PROFILE_DEL                 35234
#define IDS_PROFILE_DEL_INF             35235
#define IDS_INFO_RELOAD                 35236
#define IDS_INFO_COREAVC                35237
#define IDS_INFO_ASSEXP                 35238
#define IDS_INPUT_NONE                  35239
#define IDS_INPUT_RIGHT                 35240
#define IDS_INPUT_LEFT                  35241
#define IDS_INPUT_UP                    35242
#define IDS_INPUT_DOWN                  35243
#define IDS_INPUT_INS                   35244
#define IDS_INPUT_DEL                   35245
#define IDS_INPUT_SPACE                 35246
#define IDS_INPUT_ENTER                 35247
#define IDS_INPUT_LC                    35248
#define IDS_INPUT_LD                    35249
#define IDS_INPUT_RC                    35250
#define IDS_INPUT_RD                    35251
#define IDS_INPUT_MC                    35252
#define IDS_INPUT_MD                    35253
#define IDS_INPUT_WF                    35254
#define IDS_INPUT_WB                    35255
#define IDS_INPUT_X1C                   35256
#define IDS_INPUT_X1D                   35257
#define IDS_INPUT_X2C                   35258
#define IDS_INPUT_X2D                   35259
#define IDS_INPUT_RF                    35260
#define IDS_INPUT_RB                    35261
#define IDS_INPUT_JL                    35262
#define IDS_INPUT_JR                    35263
#define IDS_INPUT_JU                    35264
#define IDS_INPUT_JD                    35265
#define IDS_INPUT_J1                    35266
#define IDS_INPUT_J2                    35267
#define IDS_INPUT_J3                    35268
#define IDS_INPUT_J4                    35269
#define IDS_INPUT_CMD                   35270
#define IDS_INPUT_VAL                   35271
#define IDS_INPUT_KEY                   35272
#define IDS_INPUT_SEEK                  35273
#define IDS_INPUT_SUBT                  35274
#define IDS_INPUT_PTUS                  35275
#define IDS_INPUT_PTS                   35276
#define IDS_INPUT_ALTS                  35277
#define IDS_INPUT_PANS                  35278
#define IDS_INPUT_PAUS                  35279
#define IDS_INPUT_SCRS                  35280
#define IDS_INPUT_KEEP                  35281
#define IDS_INPUT_FRAD                  35282
#define IDS_INPUT_OSD                   35283
#define IDS_INPUT_QUIT                  35284
#define IDS_INPUT_MUTE                  35285
#define IDS_INPUT_SWIA                  35286
#define IDS_INPUT_SWIF                  35287
#define IDS_INPUT_SUBS                  35288
#define IDS_INPUT_SUBA                  35289
#define IDS_INPUT_SWIV                  35290
#define IDS_INPUT_VOFS                  35291
#define IDS_INPUT_VOOT                  35292
#define IDS_INPUT_RELO                  35293
#define IDS_INPUT_FRAS                  35294
#define IDS_INPUT_SPES                  35295
#define IDS_INPUT_SPEI                  35296
#define IDS_INPUT_BALA                  35297
#define IDS_INPUT_VOLU                  35298
#define IDS_INPUT_SUBP                  35299
#define IDS_INPUT_CONT                  35300
#define IDS_INPUT_BRIG                  35301
#define IDS_INPUT_SATU                  35302
#define IDS_INPUT_GAMM                  35303
#define IDS_INPUT_HUE                   35304
#define IDS_INPUT_AUDD                  35305
#define IDS_INPUT_SUBD                  35306
#define IDS_INPUT_CUST                  35307
#define IDS_INPUT_CDEL                  35308
#define IDS_INPUT_REUS                  35309
#define IDS_INPUT_CONF                  35310
#define IDS_INPUT_SET                   35311
#define IDS_INPUT_SETNONE               35312
#define IDS_INPUT_INNER                 35313
#define IDS_INPUT_INMOS                 35314
#define IDS_INPUT_ADD                   35315
#define IDS_INPUT_DEC                   35316
#define IDS_INPUT_SUBSZ                 35317
#define IDS_INPUT_LOOP                  35318
#define IDS_INPUT_LOOPIF                35319
#define IDS_INPUT_RESIZE                35320
#define IDS_INPUT_SIZEIF                35321
#define IDS_INPUT_POS                   35322
#define IDS_INPUT_POSIF                 35323
#define IDS_INPUT_FS                    35324
#define IDS_INPUT_SYS                   35325
#define IDS_INPUT_FSR                   35326
#define IDS_INPUT_FSRIF                 35327
#define IDS_INPUT_CHAP                  35328
#define IDS_INPUT_ANGLE                 35329
#define IDS_INPUT_ANGLE2                35330
#define IDS_INPUT_TITLE                 35330
#define IDS_INFO_BOOST                  35331
#define IDS_INPUT_DVDDIR                35332
#define IDS_INPUT_DVDSEL                35333
#define IDS_INPUT_DVDROOT               35334
#define IDS_INPUT_DVDDIR2               35335
#define IDS_INPUT_DVDPRE                35336
#define IDS_VIDEO_VONV                  35337
#define IDS_VIDEO_VOATI                 35338
#define IDS_VIDEO_VOGL4                 35339
#define IDS_VIDEO_VOGL2                 35340
#define IDS_VIDEO_VOGL6                 35341
#define IDS_VIDEO_VOGL0                 35342
#define IDS_INFO_REALTIME               35343
#define IDS_DECODE_THREADS              35344
#define IDS_DECODE_THREADS_INFO         35345
#define IDS_AUDIO_DELAY                 35346
#define IDS_AUDIO_DELAY_INFO            35347
#define IDS_VIDEO_VOD3D                 35348
#define IDS_AUDIO_STM                   35349
#define IDS_AUDIO_STM_INFO              35350
#define IDS_ASSOS_AVS                   35351
#define IDS_MESSAGE_AVS                 35352
#define IDS_VIDEO_SCA                   35353
#define IDS_VIDEO_CROI2                 35354
#define IDS_VIDEO_SCAI                  35354

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
