#include "StdAfx.h"
#include "resource.h"
#include "ResStr.h"

#define ResStr(id) CString(MAKEINTRESOURCE(id))

CResStr rStr;

void CResStr::LoadString()
{

	title = ResStr(IDS_PLAYER_NAME);
	player = ResStr(IDS_STRING30210);
	gui = ResStr(IDS_STRING30215);
	other = ResStr(IDS_STRING30220);
	assoc = ResStr(IDS_STRING30217);
	hotkey = ResStr(IDS_STRING30216);

	add = ResStr(IDS_STRING30221);
	del = ResStr(IDS_STRING30222);
	set_assoc = ResStr(IDS_STRING30223);
	update_assoc = ResStr(IDS_STRING30224);
	btn_ok = ResStr(IDS_STRING30225);
	btn_cancle = ResStr(IDS_STRING30226);
	btn_apply = ResStr(IDS_STRING30227);
	check_update = ResStr(IDS_STRING30228);

	lang = ResStr(IDS_STRING30229);
	skin = ResStr(IDS_STRING30230);
	ctlalpha = ResStr(IDS_STRING30231);
	ontop = ResStr(IDS_STRING30232);
	autohide = ResStr(IDS_STRING30233);
	mintray = ResStr(IDS_STRING30234);
	extra = ResStr(IDS_STRING30235);

	cwindow = ResStr(IDS_STRING30236);
	cskinb = ResStr(IDS_STRING30237);
	cskinc = ResStr(IDS_STRING30238);
	cautoh = ResStr(IDS_STRING30239);
	ctitle = ResStr(IDS_STRING30240);
	cmenu = ResStr(IDS_STRING30241);
	crmenu = ResStr(IDS_STRING30242);

	piority = ResStr(IDS_STRING30243);
	monitor = ResStr(IDS_STRING30244);
	async = ResStr(IDS_STRING30245);
	loops = ResStr(IDS_STRING30246);
	aplay = ResStr(IDS_STRING30247);
	cache = ResStr(IDS_STRING30248);
	log = ResStr(IDS_STRING30249);

	systheme = ResStr(IDS_PLAYER_THEME);

	ontop_none = ResStr(IDS_PLAYER_NONE);
	ontop_always = ResStr(IDS_PLAYER_ALLWAYS);
	ontop_playing = ResStr(IDS_PLAYER_PLAYING);

	hide_no = ResStr(IDS_PLAYER_HIDE_NO);
	hide_m = ResStr(IDS_PLAYER_HIDE_M);
	hide_a = ResStr(IDS_PLAYER_HIDE_A);

	tray_ta = ResStr(IDS_PLAYER_TASK);
	tray_tr = ResStr(IDS_PLAYER_TRAY);
	tray_trs = ResStr(IDS_PLAYER_TRAYSTOP);
		
	piority1 = ResStr(IDS_PLAYER_PREALTIME);
	piority2 = ResStr(IDS_PLAYER_PHIGH);
	piority3 = ResStr(IDS_PLAYER_PHNORMAL);
	piority4 = ResStr(IDS_PLAYER_PNORMAL);
	piority5 = ResStr(IDS_PLAYER_PLNORMAL);
	piority6 = ResStr(IDS_PLAYER_PIDLE);

	async0 = ResStr(IDS_PLAYER_AS_NO);
	async1 = ResStr(IDS_PLAYER_AS_NORMAL);
	async2 = ResStr(IDS_PLAYER_AS_FAST);
	async3 = ResStr(IDS_PLAYER_AS_FLV);
	async4 = ResStr(IDS_PLAYER_AS_FLVEX);
	async5 = ResStr(IDS_PLAYER_AS_AVI);

	playna = ResStr(IDS_PLAYER_NOUSE);
	playex = ResStr(IDS_PLAYER_EX);

	loopf = ResStr(IDS_PLAYER_FILE);
	loopl = ResStr(IDS_PLAYER_LIST);

	logn = ResStr(IDS_PLAYER_LOG_NO);
	log0 = ResStr(IDS_PLAYER_LOG);
	log1 = ResStr(IDS_PLAYER_LOG_V1);
	log2 = ResStr(IDS_PLAYER_LOG_V2);
	log3 = ResStr(IDS_PLAYER_LOG_V3);
	log4 = ResStr(IDS_PLAYER_LOG_V4);
	log5 = ResStr(IDS_PLAYER_LOG_V5);
	logc = ResStr(IDS_STRING30250);

	warning = ResStr(IDS_STRING30251);
	notshow = ResStr(IDS_STRING30252);
	winfo[0] = ResStr(IDS_INFO_RELOAD);
	winfo[1] = ResStr(IDS_INFO_COREAVC);
	winfo[2] = ResStr(IDS_INFO_ASSEXP);
	winfo[3] = ResStr(IDS_INFO_BOOST);
	winfo[4] = ResStr(IDS_INFO_REALTIME);

	browser = ResStr(IDS_STRING30272);

	cfulls = ResStr(IDS_STRING30253);
	crseek = ResStr(IDS_STRING30254);
	conep = ResStr(IDS_STRING30255);
	cguit = ResStr(IDS_STRING30256);
	cguip = ResStr(IDS_STRING30257);
	curl = ResStr(IDS_STRING30258);
	cquit = ResStr(IDS_STRING30259);
	cquiet = ResStr(IDS_STRING30260);
	cdouble = ResStr(IDS_STRING30261);
	cconf = ResStr(IDS_STRING30262);
	chtime = ResStr(IDS_STRING30263);
	cdvd = ResStr(IDS_STRING30264);
	creload = ResStr(IDS_STRING30265);
	cfdrop = ResStr(IDS_STRING30266);
	cidx = ResStr(IDS_STRING30267);
	cpng = ResStr(IDS_STRING30268);
	copen = ResStr(IDS_STRING30269);
	cstart = ResStr(IDS_STRING30270);
	cend = ResStr(IDS_STRING30271);


	INPUT_NONE = ResStr(IDS_INPUT_NONE);
	INPUT_LEFT = ResStr(IDS_INPUT_LEFT);
	INPUT_RIGHT = ResStr(IDS_INPUT_RIGHT);
	INPUT_UP = ResStr(IDS_INPUT_UP);
	INPUT_DOWN = ResStr(IDS_INPUT_DOWN);
	INPUT_INS = ResStr(IDS_INPUT_INS);
	INPUT_DEL = ResStr(IDS_INPUT_DEL);
	INPUT_SPACE = ResStr(IDS_INPUT_SPACE);
	INPUT_ENTER = ResStr(IDS_INPUT_ENTER);
	INPUT_LC = ResStr(IDS_INPUT_LC);
	INPUT_LD = ResStr(IDS_INPUT_LD);
	INPUT_RC = ResStr(IDS_INPUT_RC);
	INPUT_RD = ResStr(IDS_INPUT_RD);
	INPUT_MC = ResStr(IDS_INPUT_MC);
	INPUT_MD = ResStr(IDS_INPUT_MD);
	INPUT_WF = ResStr(IDS_INPUT_WF);
	INPUT_WB = ResStr(IDS_INPUT_WB);
	INPUT_X1C = ResStr(IDS_INPUT_X1C);
	INPUT_X1D = ResStr(IDS_INPUT_X1D);
	INPUT_X2C = ResStr(IDS_INPUT_X2C);
	INPUT_X2D = ResStr(IDS_INPUT_X2D);
	INPUT_RF = ResStr(IDS_INPUT_RF);
	INPUT_RB = ResStr(IDS_INPUT_RB);

	INPUT_JL = ResStr(IDS_INPUT_JL);
	INPUT_JR = ResStr(IDS_INPUT_JR);
	INPUT_JU = ResStr(IDS_INPUT_JU);
	INPUT_JD = ResStr(IDS_INPUT_JD);
	INPUT_J1 = ResStr(IDS_INPUT_J1);
	INPUT_J2 = ResStr(IDS_INPUT_J2);
	INPUT_J3 = ResStr(IDS_INPUT_J3);
	INPUT_J4 = ResStr(IDS_INPUT_J4);

	INPUT_CMD = ResStr(IDS_INPUT_CMD);
	DECODE_INF = ResStr(IDS_DECODE_INF);
	INPUT_VAL	 = ResStr(IDS_INPUT_VAL);
	INPUT_KEY = ResStr(IDS_INPUT_KEY);

	INPUT_INNER = ResStr(IDS_INPUT_INNER);
	INPUT_ADD = ResStr(IDS_INPUT_ADD);
	INPUT_SUBSZ = ResStr(IDS_INPUT_SUBSZ);

	INPUT_DEC = ResStr(IDS_INPUT_DEC);

	INPUT_LOOP = ResStr(IDS_INPUT_LOOP);
	INPUT_LOOPIF = ResStr(IDS_INPUT_LOOPIF);
	INPUT_WINRESIZE = ResStr(IDS_INPUT_WINRESIZE);

	INPUT_RESIZE = ResStr(IDS_INPUT_RESIZE);
	INPUT_RIGHT = ResStr(IDS_INPUT_RIGHT);

	INPUT_POS = ResStr(IDS_INPUT_POS);
	INPUT_POSIF = ResStr(IDS_INPUT_POSIF);
	INPUT_LEFT = ResStr(IDS_INPUT_LEFT);

	INPUT_FS = ResStr(IDS_INPUT_FS);
	INPUT_ENTER = ResStr(IDS_INPUT_ENTER);

	INPUT_SYS = ResStr(IDS_INPUT_SYS);

	INPUT_DVDDIR = ResStr(IDS_INPUT_DVDDIR);
	INPUT_DVDDIR2 = ResStr(IDS_INPUT_DVDDIR2);
	INPUT_DVDSEL= ResStr(IDS_INPUT_DVDSEL);
	INPUT_DVDROOT= ResStr(IDS_INPUT_DVDROOT);
	INPUT_DVDPRE= ResStr(IDS_INPUT_DVDPRE);
	INPUT_FSR= ResStr(IDS_INPUT_FSR);
	INPUT_FSRIF = ResStr(IDS_INPUT_FSRIF);
	INPUT_RC = ResStr(IDS_INPUT_RC);
	INPUT_CONF = ResStr(IDS_INPUT_CONF);
	INPUT_REUS = ResStr(IDS_INPUT_REUS);
	INPUT_CUST = ResStr(IDS_INPUT_CUST);
	INPUT_CDEL = ResStr(IDS_INPUT_CDEL);

	INPUT_SETNONE = ResStr(IDS_INPUT_SETNONE);
	INPUT_SET = ResStr(IDS_INPUT_SET);

	INPUT_SEEK= ResStr(IDS_INPUT_SEEK);
	INPUT_SUBT= ResStr(IDS_INPUT_SUBT);
	INPUT_PTUS= ResStr(IDS_INPUT_PTUS);
	INPUT_PTS= ResStr(IDS_INPUT_PTS);
	INPUT_ALTS= ResStr(IDS_INPUT_ALTS);
	INPUT_PANS= ResStr(IDS_INPUT_PANS);
	INPUT_PAUS= ResStr(IDS_INPUT_PAUS);
	INPUT_SCRS= ResStr(IDS_INPUT_SCRS);
	INPUT_KEEP= ResStr(IDS_INPUT_KEEP);
	INPUT_FRAD= ResStr(IDS_INPUT_FRAD);
	INPUT_OSD= ResStr(IDS_INPUT_OSD);
	INPUT_QUIT= ResStr(IDS_INPUT_QUIT);
	INPUT_MUTE= ResStr(IDS_INPUT_MUTE);

	INPUT_SWIA= ResStr(IDS_INPUT_SWIA);
	INPUT_SWIF= ResStr(IDS_INPUT_SWIF);
	INPUT_CHAP= ResStr(IDS_INPUT_CHAP);
	INPUT_TITLE= ResStr(IDS_INPUT_TITLE);
	INPUT_ANGLE= ResStr(IDS_INPUT_ANGLE);

	INPUT_SUBS= ResStr(IDS_INPUT_SUBS);
	INPUT_SUBA= ResStr(IDS_INPUT_SUBA);
	INPUT_SWIV= ResStr(IDS_INPUT_SWIV);
	INPUT_VOFS= ResStr(IDS_INPUT_VOFS);
	INPUT_VOOT= ResStr(IDS_INPUT_VOOT);
	INPUT_RELO= ResStr(IDS_INPUT_RELO);
	INPUT_FRAS= ResStr(IDS_INPUT_FRAS);
	INPUT_SPES= ResStr(IDS_INPUT_SPES);
	INPUT_SPEI= ResStr(IDS_INPUT_SPEI);
	INPUT_BALA= ResStr(IDS_INPUT_BALA);

	INPUT_VOLU= ResStr(IDS_INPUT_VOLU);
	INPUT_SUBP= ResStr(IDS_INPUT_SUBP);
	INPUT_CONT= ResStr(IDS_INPUT_CONT);
	INPUT_BRIG= ResStr(IDS_INPUT_BRIG);
	INPUT_SATU= ResStr(IDS_INPUT_SATU);
	INPUT_GAMM= ResStr(IDS_INPUT_GAMM);
	INPUT_HUE= ResStr(IDS_INPUT_HUE);

	INPUT_AUDD= ResStr(IDS_INPUT_AUDD);
	INPUT_SUBD= ResStr(IDS_INPUT_SUBD);

	autos = ResStr(IDS_PLAYER_AUTO);
	nos = ResStr(IDS_PLAYER_NO);
}

